from common.modules.enum_utils import EnumStr
from enum import Enum


class CurvesReference(EnumStr, Enum):
    """may needs to go into a database to manage naming convention dynamically"""
    ts = 'ts'
    profit = 'profit'
    profit_return = 'delta_profit_rel'
    rolling_max_profit = 'rolling_max_profit'
    trailing_profit = 'trailing_profit'
    EMA_540_300d_return = 'EMA_540_300d_return'
    MOM_real_23_return = 'MOM_real_23_return'
    MOM_real_360_return = 'MOM_real_360_return'
    trailing_stop_loss = 'trailing_stop_loss'
    long_exit = 'long_exit'
    short_exit = 'short_exit'
    trail_profit_stop_price = 'trail_profit_stop_price'
    action = 'action'
    rl_action = 'rl_action'
    rl_action_ls = 'rl_action_ls'
    rl_action_exit = 'rl_action_exit'
    rl_risk_reward_ls = 'rl_risk_reward_ls'
    rl_risk_reward_neutral = 'rl_risk_reward_neutral'
    rl_risk_reward_ls_actual = 'rl_risk_reward_ls_actual'
    rl_risk_reward_neutral_actual = 'rl_risk_reward_neutral_actual'
    p_long = 'p_long'
    p_short = 'p_short'
    p_long_pre = 'p_long_pre'
    p_short_pre = 'p_short_pre'
    elapsed = 'elapsed'
    close = 'close'
    ohlc_mid = 'ohlc_mid'
    ohlc_ask = 'ohlc_ask'
    ohlc_bid = 'ohlc_bid'
    ohlc_trade = 'ohlc_trade'
    regr_reward_action = 'regr_reward_action'
    regr_reward_ls_weighted = 'regr_reward_ls_weighted'
    regr_reward_neutral_weighted = 'regr_reward_neutral_weighted'
