talib_out_2_results = ['MAMA', 'HT_PHASOR', 'HT_SINE', 'STOCH', 'STOCHF', 'STOCHRSI', 'AROON', 'MINMAX', 'MINMAXINDEX']
talib_out_3_results = ['BBANDS', 'MACD', 'MACDEXT', 'MACDFIX']
talib_timeperiod = [
    # Overlap studies
    'DEMA', 'EMA', 'KAMA', 'MIDPOINT', 'MIDPRICE', 'SMA', 'TEMA', 'TRIMA', 'WMA',
    # Momentum
    'ADX', 'ADXR', 'AARON', 'AROONOSC', 'CCI', 'CMO', 'DX', 'MFI', 'MINUS_DI', 'MINUS_DM', 'MOM', 'PLUS_DI',
    'PLUS_DM',
    'ROC', 'ROCP', 'ROCR100', 'RSI', 'TRIX', 'WILLR',
    # volatility
    'ATR', 'NATR',
    # statistic
    'BETA', 'CORREL', 'LINEARREG', 'LINEARREG_INTERCEPT', 'LINEARREG_SLOPE', 'TSF'
    # Math Operators
                                                                             'MAX', 'MAXINDEX', 'MIN',
    'MININDEX', 'MINMAX', 'MINMAXINDEX', 'SUM',
    # Volumne
    'AD', 'ADOSC', 'OBV'
]
talib_gt_1_param = {
    # Overlap studies
    'BBANDS': ['timeperiod', 'nbdevup', 'nbdevdn', 'matype'],
    'MA': ['timeperiod', 'matype'],
    'MAMA': ['fastlimit', 'slowlimit'],
    'MAVP': ['periods', 'minperiod', 'maxperiod=', 'matype'],
    'SAR': ['acceleration', 'maximum'],
    'SAREXT': ['startvalue', 'offsetonreverse', 'accelerationinitlong', 'accelerationlong',
               'accelerationmaxlong', 'accelerationinitshort', 'accelerationshort', 'accelerationmaxshort'],
    'T3': ['timeperiod', 'vfactor'],
    # Momentum
    'APO': ['fastperiod', 'slowperiod', 'matype'],
    'MACD': ['fastperiod', 'slowperiod', 'signalperiod'],
    'MACDEXT': ['fastperiod', 'fastmatype', 'slowperiod', 'slowmatype', 'signalperiod', 'signalmatype'],
    'MACDFIX': ['signalperiod'],
    'PPO': ['fastperiod', 'slowperiod', 'matype'],
    'STOCH': ['fastk_period', 'slowk_period', 'slowk_matype', 'slowd_period', 'slowd_matype'],
    'STOCHF': ['fastk_period', 'fastd_period', 'fastd_matype'],
    'STOCHRSI': ['timeperiod', 'fastk_period', 'fastd_period', 'fastd_matype'],
    'ULTOSC': ['timeperiod1', 'timeperiod2', 'timeperiod3'],
    # volume indicators#
    'ADOSC': ['fastperiod', 'slowperiod'],
    # pattern recog
    'CDLABANDONEDBABY': ['penetration'],
    'CDLDARKCLOUDCOVER': ['penetration'],
    'CDLEVENINGDOJISTAR': ['penetration'],
    'CDLEVENINGSTAR': ['penetration'],
    'CDLMATHOLD': ['penetration'],
    'CDLMORNINGDOJISTAR': ['penetration'],
    'CDLMORNINGSTAR': ['penetration'],
    # Statistic:
    'STDDEV': ['timeperiod', 'nbdev'],
    'VAR': ['timeperiod', 'nbdev']
}
talib_excluded = ['MAVP', 'TA_MINMAX']
talib_selected = [
    # 'ADX',
    'APO', 'AROON',
    'AROONOSC',
    'BOP',
    'CCI',
    'CMO',
    # 'MACD',
    'MOM', 'PPO',
    # 'ROC', 'ROCP',
    'RSI',
    'STOCH',
    'ULTOSC',
    'WILLR',
    'STDDEV',
    # 'VAR',
    'NATR',
    # 'ADXR', 'ATR'
    'ADOSC',
    # 'AD', 'OBV'
]  # , 'MFI'],'AD',

talib_selected_old = ['HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDMODE',
                      'MINMAX', 'SUB',
                      'ADX', 'APO', 'AROON', 'AROONOSC', 'BOP', 'CCI', 'CMO', 'DX', 'MACD',
                      'MFI', 'MINUS_DI', 'MINUS_DM', 'MOM', 'PLUS_DI', 'PLUS_DM', 'PPO',
                      'ROC', 'ROCP', 'ROCR100', 'RSI', 'STOCH', 'STOCHF', 'STOCHRSI', 'TRIX',
                      'ULTOSC', 'WILLR', 'BBANDS', 'DEMA', 'EMA', 'HT_TRENDLINE', 'KAMA',
                      'MA', 'MAMA', 'MAVP', 'MIDPRICE', 'SAR', 'SAREXT', 'SMA',
                      'T3', 'TEMA', 'TRIMA', 'WMA', 'AVGPRICE', 'WCLPRICE', 'BETA', 'CORREL',
                      'LINEARREG', 'LINEARREG_ANGLE', 'LINEARREG_SLOPE', 'STDDEV', 'TSF',
                      'VAR', 'NATR', 'TRANGE']
talib_d1 = ['HT_DCPERIOD',
            'HT_DCPHASE',
            'HT_PHASOR',
            'HT_SINE',
            'HT_TRENDMODE',
            'ADX',
            'BOP',
            'CCI',
            'CMO',
            'DX',
            'MACD',
            'MINUS_DI',
            'MOM',
            'PLUS_DI',
            'PPO',
            'RSI',
            'STOCH',
            'STOCHF',
            'STOCHRSI',
            'KAMA',
            'MA',
            'SMA',
            'T3',
            'TEMA',
            'TRIMA',
            'WMA',
            'BETA',
            'AD',
            ]
talib_d2 = ['HT_DCPERIOD',
            'HT_DCPHASE',
            'HT_PHASOR',
            'HT_SINE',
            'HT_TRENDMODE',
            'ADX',
            'BOP',
            'CCI',
            'CMO',
            'DX',
            'MACD',
            'MINUS_DI',
            'MOM',
            'PLUS_DI',
            'PPO',
            'RSI',
            'STOCH',
            'STOCHF',
            'STOCHRSI',
            'KAMA',
            'MA',
            'SMA',
            'T3',
            'TEMA',
            'TRIMA',
            'WMA',
            'BETA',
            'AD',
            ]
talib_top_x_ind = ['HT_DCPERIOD',
                   'HT_DCPHASE',
                   'HT_PHASOR',
                   'HT_SINE',
                   'HT_TRENDMODE',
                   'MAXINDEX',
                   'MININDEX',
                   'MINMAX',
                   'MINMAXINDEX',
                   'SUB',
                   'ADX',
                   'BOP',
                   'CCI',
                   'CMO',
                   'DX',
                   'MACD',
                   'MINUS_DI',
                   'MOM',
                   'PLUS_DI',
                   'PPO',
                   'ROC',
                   'ROCP',
                   'ROCR100',
                   'RSI',
                   'STOCH',
                   'STOCHF',
                   'STOCHRSI',
                   'TRIX',
                   'ULTOSC',
                   'WILLR',
                   'BETA',
                   ]
talib_cross_x = ['PPO', 'ROC', 'ROCP', 'ROCR100', 'TRIX', 'BETA']
talib_around_x = ['HT_DCPERIOD', 'HT_DCPHASE', 'HT_PHASOR', 'HT_SINE', 'HT_TRENDMODE',
                  'ADX', 'BOP', 'CCI', 'CMO', 'MACD', 'MOM', 'PPO', 'ROC', 'ROCP', 'ROCR100', 'RSI', 'STOCH', 'STOCHF',
                  'STOCHRSI', 'TRIX', 'BETA', 'AD']
talib_cross_mean = ['RSI', 'STOCH', 'STOCHF', 'STOCHRSI', 'ULTOSC', 'WILLR']
talib_around_mean = ['DX', 'RSI', 'STOCH', 'STOCHF', 'STOCHRSI', 'ULTOSC', 'WILLR']
talib_feats_crossed = ['SMA', 'DEMA', 'EMA', 'WMA']
talib_above_band = ['BBANDS']
